name: Terraform AWS Academy Deploy Test

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação Terraform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Terraform Init
      working-directory: src/terraform
      run: terraform init
      
    - name: Terraform Validate
      working-directory: src/terraform
      run: terraform validate
      
    - name: Terraform Plan
      if: github.event.inputs.action == 'plan'
      working-directory: src/terraform
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      working-directory: src/terraform
      run: terraform apply -auto-approve
      
    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      working-directory: src/terraform
      run: terraform destroy -auto-approve
      
    - name: Show State
      if: github.event.inputs.action != 'destroy'
      working-directory: src/terraform
      run: terraform show